AWSTemplateFormatVersion: 2010-09-09

Parameters:
  CidrIpFromInternet:
    Type: String
    Description: CIDR IP range for allowing access from the internet
    Default: !Sub "{{resolve:ssm:/network/cidr_ip}}"

Resources: 
#ControleNodeのセキュリティグループ
  ControlNodeSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: ControlNodeSecurityGroup
      GroupDescription: Security group for SSH HTTP access
      VpcId: !ImportValue Lesson13vpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref CidrIpFromInternet
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: -1
      Tags:
        - Key: Name
          Value: ControlNodeSecurityGroup
#TargetNodeのセキュリティグループ
  Lesson13Ec2SecurityGroup: 
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: Lesson13Ec2SecurityGroup
      GroupDescription: Security group for SSH HTTP access
      VpcId: !ImportValue Lesson13VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !GetAtt ControlNodeSecurityGroup
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          SourceSecurityGroupId: !Ref ControlNodeSecurityGroup
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !GetAtt ALBSecurity.GroupId
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: -1
      Tags:
        - Key: Name
          Value: Lesson13Ec2SecurityGroup
#ALBのセキュリティグループ
  ALBSecurity:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: ALBSecurity
      GroupDescription: ALB for HTTP access
      VpcId: !ImportValue Lesson13VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: -1
      Tags:
        - Key: Name
          Value: L13ALBSecurity 
#RDSのセキュリティグループ  
  L13RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !ImportValue Lesson13VpcId
      GroupDescription: Access to rds is only from this ec2
      SecurityGroupIngress:
          IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !GetAtt Lesson13Ec2SecurityGroup.GroupId
      Tags:
        - Key: Name
          Value: L13RDSSecurity     
#Output Parameters
Outputs:
    L13Ec2SecurityGpId:
      Description: L13Ec2SecurityGroup
      Value: !Ref Lesson13Ec2SecurityGroup
      Export: 
        Name: L13Ec2SecurityGpId
    ALBSecurityGpId:
      Description: ALBSecurityGroup
      Value: !Ref ALBSecurity
      Export: 
        Name: ALBSecurityGpId
    L13RDSSecurityGpId:
      Description: L13RDSSecurityGroup
      Value: !Ref L13RDSSecurityGroup
      Export: 
        Name: L13RDSSecurityGpId       
    ControlNodeSecurityGroupId:
      Description: ControlNodeSecurityGroup
      Value: !Ref ControlNodeSecurityGroup
      Export: 
        Name: ControlNodeSecurityGroupId
