
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.2.0

jobs:
  cloud-formation:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
          region: $AWS_DEFAULT_REGION
      - run:
          name: cloud-formation deploy
          command: 
            aws cloudformation deploy --template-file cloud/network.yml --stack-name network
          
workflows: 
   cloud-formation-workflow: 
      jobs:
        - cloud-formation
